---
- name: greetins 
  hosts: all
  gather_facts: true
  debugger: always
  vars:
    greetings: "hello i am the fixed variable!"
  tasks:
    - name: printing the var.
      debug:
        msg: "{{ greetings }}"







# - name: Gather server info
#   hosts: all
#   tasks:
#     - name: Print server role
#       debug:
#         msg: "Server role is {{ ansible_local.server_info.node_role }}."

#     - name: Check for application presence
#       debug:
#         msg: "Applications installed: {{ ansible_local.server_info.applications }}."

#     - name: Display inventory location
#       debug:
#         msg: >
#           This server is located in {{ ansible_local.server_info.inventory.datacenter }},
#           rack {{ ansible_local.server_info.inventory.rack }},
#           unit {{ ansible_local.server_info.inventory.unit }}.

#     - name: Report hardware details
#       debug:
#         msg: >
#           Hardware specs - CPU: {{ ansible_local.server_info.hardware.cpu }},
#           Memory: {{ ansible_local.server_info.hardware.memory_gb }} GB,
#           Storage: SSD {{ ansible_local.server_info.hardware.storage_tb.ssd }} TB,
#           HDD {{ ansible_local.server_info.hardware.storage_tb.hdd }} TB.
#     - name: Set nginx_state
#       when: ansible_facts.services.nginx.state is defined
#       set_fact:
#         nginx_state: "{{ ansible_facts.services.nginx.state }}"




# - name: 'Ansible facts.'
#   hosts: all
#   gather_facts: true
#   tasks:
#     - name: Print out operating system details
#       debug:
#         msg: >-
#           os_family:
#           {{ ansible_facts.os_family }},
#           distro:
#           {{ ansible_facts.distribution }}
#           {{ ansible_facts.distribution_version }},
#           kernel:
#           {{ ansible_facts.kernel }}






# - name: Capture output of whoami command
#   hosts: all
#   become: true
#   gather_facts: true
#   tasks:  # Corrected from 'task' to 'tasks' to properly define a list of tasks
#     - command: whoami  # This is the correct command to capture the username of the user.
#       register: login  # Correct alignment under the task.

#     # Optionally, you can add a task to debug and print the result to verify it
#     - debug:
#         msg: "The logged in user is {{ login.stdout }}"





# - name: simple playbook for managing a package
#   hosts: all
#   become: true
#   gather_facts: true
#   vars:
#     package: tree
#     package_state: absent  
#   tasks:
#     - name: Ensure the state of the tree package
#       apt:
#         update_cache: true
#         name: "{{ package }}"
#         state: "{{ package_state }}"
#     - name: debug
#       debug: 
#         msg: "The variable is {{ package }}, and {{ package_state }}"

  # vars:
  #   file_path: "/root/"
  #   file_name: "holla_Ansible.txt"

  # tasks:
  #   - name: copy the file to the source
  #     ansible.builtin.template:
  #       src: template.txt.j2
  #       dest: "{{ file_path }}{{ file_name }}"

  #   - name: creating the file now
  #     ansible.builtin.file:
  #       path: "{{ file_path }}{{ file_name }}"
  #       state: touch
  #   - name: write some content into the file.
  #     shell:
  #       cmd: "echo holllllla again from the last module! >> '{{ file_path }}{{ file_name}}'"
    
 